Repository CloudNationHQ/terraform-azure-wafwp, pull requests merged in 2024-11, with the labels that each got.

#2 feat: add initial resources
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/question.yml
  .github/dependabot.yml
  .github/pull_request_template.md
  .github/release-please.yml
  .github/workflows/linting.yml
  .github/workflows/validate.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  Makefile
  README.md
  SECURITY.md
  TESTING.md
  examples/custom_rules/README.md
  examples/custom_rules/main.tf
  examples/custom_rules/terraform.tf
  examples/default/README.md
  examples/default/main.tf
  examples/default/terraform.tf
  examples/managed-rules/README.md
  examples/managed-rules/main.tf
  examples/managed-rules/terraform.tf
  main.tf
  outputs.tf
  terraform.tf
  tests/deploy_test.go
  tests/go.mod
  tests/go.sum
  variables.tf
Labels: new module

#4 fix: fix module references
  examples/custom_rules/main.tf
  examples/default/main.tf
  examples/managed-rules/main.tf
Labels: bug

#7 fix: allow multiple managed rulsets
  README.md
  examples/custom_rules/README.md
  examples/custom_rules/main.tf
  examples/default/README.md
  examples/default/main.tf
  examples/managed-rules/README.md
  examples/managed-rules/main.tf
  main.tf
Labels: bug

#9 fix: Add policy_settings object
  examples/default/main.tf
  main.tf
Labels: enhancement

#11 feat: add policy settings in all usages
  examples/custom_rules/main.tf
  examples/default/main.tf
  examples/managed-rules/main.tf
Labels: enhancement
